<?php
/**
 * The Brand (the page with the slug "brand").
 */
get_header();
?>
	<main>
		<!-- ===== Intro: what KYNARA makes, then a banner across the container (replaced the hero) ===== -->
		<section class="brand-intro">
			<div class="wrap">
				<h1 class="brand-intro__title" data-i18n-html="brand.intro.title">Sustainable composites for<br>floors, walls and structures</h1>
				<div class="img-box img-box--parallax brand-intro__media"><img src="<?php echo esc_url( kynara_asset( 'images/brand-banner.webp' ) ); ?>" alt="A couple dancing on a sunlit forest path beside a bicycle" fetchpriority="high"></div>
			</div>
		</section>

		<div class="brand-body">
			<div class="wrap">
				<section class="feature" id="craftsmanship">
					<div class="feature__text">
						<h2 class="feature__title" data-i18n-html="brand.craft.title">Layers of<br>Craftsmanship</h2>
						<div class="two-col">
							<p data-i18n="brand.craft.a">The KY in KYNARA comes from kayu, the Indonesian word for wood, and wood is where our craft begins. Each panel pairs a mineral composite core with a wood composite face, reinforced with recycled polymer: engineered with intention, so nothing is accidental.</p>
							<p data-i18n="brand.craft.b">The surface is finished with NanoWood™, our own coating method of around seven layers of pigments and coatings, for stronger protection and a grain and texture true to real wood.</p>
						</div>
					</div>
					<div class="img-box img-box--parallax"><img src="<?php echo esc_url( kynara_asset( 'images/meeting-with-forest.webp' ) ); ?>" alt="Meeting table beneath an opening to the forest" loading="lazy"></div>
				</section>

				<section class="feature feature--reverse" id="sustainability">
					<div class="img-box img-box--parallax"><img src="<?php echo esc_url( kynara_asset( 'images/cosmos_789092184.webp' ) ); ?>" alt="Person reading on a leather sofa surrounded by plants" loading="lazy"></div>
					<div class="feature__text">
						<div>
							<h2 class="feature__title" data-i18n-html="brand.sustain.title">The Sustainable<br>Alternatives</h2>
							<ul class="stats">
								<li class="stat"><span class="stat__value" data-count-from="0" data-count-to="60" data-count-suffix="%">60%</span><span class="stat__label" data-i18n="brand.stat1">rice husk from local farms</span></li>
								<li class="stat"><span class="stat__value" data-count-from="0" data-count-to="30" data-count-suffix="%">30%</span><span class="stat__label" data-i18n="brand.stat2">recycled plastic post-consumer</span></li>
								<li class="stat"><span class="stat__value" data-count-prefix="~" data-count-from="0" data-count-to="600" data-count-suffix="kg">~600kg</span><span class="stat__label" data-i18n="brand.stat3">plastic saved from production</span></li>
								<li class="stat"><span class="stat__value" data-count-from="250" data-count-to="0">0</span><span class="stat__label" data-i18n="brand.stat4">deforestation for production of goods</span></li>
							</ul>
						</div>
						<div class="two-col">
							<p data-i18n="brand.sustain.a">KYNARA is an eco-friendly hybrid material, sourced responsibly from farmers and recycling facilities. Rice husk from the harvests of Nusantara is blended with post-consumer plastics such as shampoo bottles and bottle caps, so what would be waste becomes something built to last.</p>
							<p data-i18n="brand.sustain.b">We use recycled wood in our products too, so making them never means cutting down a tree: zero deforestation. A circular material, with local farmers and recycling industries as the backbone of our ecosystem, and products that let people live close to nature without destroying it.</p>
						</div>
					</div>
				</section>

			</div>

			<!-- ===== Layer breakdown (css/layers.css + js/layers.js) =====
			     Its own block, outside the features' .wrap (its frame carries its own .wrap). The drawing is
			     generated by layers.js and fits inside the page margins; the label order must match LAYERS
			     there (top layer first). -->
			<section class="layers" id="our-product" data-layers aria-labelledby="layers-title">
				<div class="wrap layers__frame">
					<h2 class="layers__title" id="layers-title" data-i18n="layers.title">Our Product</h2>
					<div class="layers__stage">
						<ul class="layers__labels">
							<li><span class="layers__label"><span class="layers__label-text"><span class="layers__label-name" data-i18n="layers.coating.name">(PU) Clear Coating</span><span class="layers__label-sub" data-i18n="layers.coating.sub"></span></span></span></li>
							<li><span class="layers__label"><span class="layers__label-text"><span class="layers__label-name" data-i18n="layers.pigment.name">Nanowood</span><span class="layers__label-sub" data-i18n="layers.pigment.sub">Pigment</span></span></span></li>
							<li><span class="layers__label"><span class="layers__label-text"><span class="layers__label-name" data-i18n="layers.teak.name">Teak Wood</span><span class="layers__label-sub" data-i18n="layers.teak.sub">Composite</span></span></span></li>
							<li><span class="layers__label"><span class="layers__label-text"><span class="layers__label-name" data-i18n="layers.mineral.name">Mineral</span><span class="layers__label-sub" data-i18n="layers.mineral.sub">Composite</span></span></span></li>
						</ul>
						<div class="layers__art" aria-hidden="true"></div>
						<svg class="layers__leaders" aria-hidden="true"></svg>
					</div>
				</div>
			</section>

			<div class="wrap">
				<section class="feature feature--last" id="applications">
					<div class="feature__text">
						<h2 class="feature__title" data-i18n-html="brand.apps.title">Limitless<br>Applications</h2>
						<div class="two-col">
							<p data-i18n="brand.apps.a">From cladding and wall panels to decking, ceilings and furniture, KYNARA is made for the way people live: weather-resistant, waterproof, fire resistant and termite-free, with high load resistance and low maintenance.</p>
							<p data-i18n="brand.apps.b">Every panel is ASTM tested, by third-party labs and in-house, from 5,000 hours of accelerated weathering to stain, impact and abrasion resistance. International standards and Nusantara identity, with neither sacrificed for the other.</p>
						</div>
					</div>
					<div class="img-box img-box--parallax"><img src="<?php echo esc_url( kynara_asset( 'images/cosmos_969656075.webp' ) ); ?>" alt="Person resting beneath a moss-covered tree sculpture" loading="lazy"></div>
				</section>
			</div>
		</div>
	</main>
<?php
get_footer();
